sirius/authorization/urls.py
from django.urls import path
from .views import *

app_name = 'authorization'

urlpatterns = [
    path('role/create/', create_role, name='create_role'),
    path('roles/', show_roles, name='show_roles'),
    path('roles/update/', update_roles, name='update_roles'),
    path('permissions/', show_permissions, name='show_permissions'),
    path('permissions/update/', update_permissions, name='update_permissions'),
    path('role/<r_pk>/delete/', delete_role, name='delete_role'),
    path('role/<r_pk>/update/', update_role, name='update_role'),

]

sirius/sirius/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name='landing'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('user/', include('user.urls')),
    path('team/', include('team.urls')),
    # path('session/', include('session.urls')),
    path('authorization/<team_pk>/', include('authorization.urls'))
]

sirius/team/urls.py
from django.urls import path
from .views import *
from django.urls.conf import include

app_name = 'team'

urlpatterns = [
    path('create/', create_team, name='create_team'),
    path('<pk>/new-team/', create_sub_team, name='create_sub_team'),
    path('<pk>/info/', team_info, name='team_info'),
    path('<pk>/send-invite/<user>/', send_invite, name='send_invite'),
    path('send-join-request/', send_join_request, name='send_join_request'),
    path('<pk>/invites/', invites, name='invites'),
    path('<pk>/join-requests/', join_requests, name='join_requests'),
    path('accept-invite/<pk>/', accept_invite, name='accept_invite'),
    path('accept-join-request/<pk>/', accept_join_request, name='accept_join_request'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('decline-invite/<pk>/', decline_invite, name='decline_invite'),
    path('leave-team/<pk>/', leave_team, name='leave_team'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('<pk>/delete', delete_team, name='delete_team'),
    path('<pk>/get_todo_list', get_todo_list, name='get_todo_list'),
    path('<pk>/add_item', create_an_item, name='create_an_item'),
    path('<pk>/edit_item/<id>', edit_an_item, name='edit_an_item'),
    path('<pk>/toggle/<id>', toggle_status, name='toggle_status'),
    path('<pk>/view-analytics/', view_analytics, name='view_analytics'),
    path('<pk>/', include('session.urls', namespace="session"))
]

sirius/user/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from session.views import user_calendar, user_bulletin

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('settings/', views.accountsettings, name='settings'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('bulletin/', user_bulletin, name='bulletin'),
    path('<u_pk>/dashboard/', views.dashboard, name='dashboard'),
    path('<u_pk>/calendar/', user_calendar, name='calendar'),
    # path('<u_pk>/settings/', views.settings, name='settings'),
]

sirius/templates/base.html
{% load tailwind_tags %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>
			College Club Management System | {% block title %}{% endblock %}
		</title>
		<script src="https://kit.fontawesome.com/3b888f4203.js" crossorigin="anonymous"></script>
		<script>
			{% block script %}
			{% endblock %}
		</script>
		{% block links %}
		{% endblock %}
		{% tailwind_css %}
		<style>
			{% block style %}
			{% endblock %}
		</style>
		<!-- fonts.google -->
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
		<!-- favicon -->
		<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
		<link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
	</head>
	{% block body %}
	{% endblock %}
</html>

sirius/templates/console.html
{% extends 'nav.html' %}

{% block title %}
{{ console.team.name }}
{% endblock %}

{% block main %}
<div class="flex flex-row w-full">
    <script>
        function showDeletePopup() {
            var popup = document.getElementById("delete-popup");
            popup.classList.toggle("hidden");
        }

        function showLeavePopup() {
            var popup = document.getElementById("leave-popup");
            popup.classList.toggle("hidden");
        }

    </script>
    <div class="flex flex-col min-w-[320px] mr-8">
        <aside>
            <nav class="text-grey w-[280px]">
                <p class="mb-8 text-[24px]">
                    {% for parent in console.parents %}
                        <a href="{% url 'team:team_info' pk=parent.id %}" class="hover:underline">{{ parent.name|upper }} / </a>
                    {% endfor %}
                    <span class="text-[36px] font-bold">{{ console.team.name|upper }}</span><span title="{{ console.team.id }}" class="cursor-help">#{{ console.team.id|truncatechars:5 }}</span>
                </p>
                <ul>
                    {% if "R-T" in console.perms %}
                    <a href="{% url 'team:team_info' pk=console.team.id %}">
                        <li class="console-navs {% if '/info/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-circle-info"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Info</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "R-C" in console.perms or "C-C" in console.perms or "U-C" in console.perms or "D-C" in console.perms %}
                    <a href="{% url 'team:session:timetable' pk=console.team.id %}">
                        <li class="console-navs {% if '/timetable/' in request.path or '/class/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-calendar-days"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Timetable</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "R-E" in console.perms or "C-E" in console.perms or "U-E" in console.perms or "D-E" in console.perms %}
                    <a href="{% url 'team:session:calendar' pk=console.team.id %}">
                        <li class="console-navs {% if '/calendar/' in request.path or '/event/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-calendar-check"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Calendar</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "R-N" in console.perms or "C-N" in console.perms or "U-N" in console.perms or "D-N" in console.perms %}
                    <a href="{% url 'team:session:notice_board' pk=console.team.id %}">
                        <li class="console-navs {% if '/notices/' in request.path or '/notice/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-circle-exclamation"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Notice Board</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    <a href="#" onclick="showLeavePopup()">
                        <li class="console-navs {% if '/leave-team/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-arrow-right-from-bracket"></i>
                            </div>
                            <div class="console-nav-link text-red">
                                <p>Leave</p>
                            </div>
                        </li>
                    </a>
                    <hr>
                    <!-- <li class="text-[24px] pb-2 pt-4 ml-8 border-2"></li> -->
                    {% if "C-T" in console.perms %}
                        <a href="{% url 'team:create_sub_team' pk=console.team.id %}">
                            <li class="console-navs {% if '/new-team/' in request.path %}active-tab{% endif %}">
                                <div class="active-indicator">
                                </div>
                                <div class="console-nav-icon">
                                    <i class="fa-solid fa-circle-plus"></i>
                                </div>
                                <div class="console-nav-link">
                                    <p>Create a Team</p>
                                </div>
                            </li>
                        </a>
                    {% endif %}
                    {% if "R-R" in console.perms or "U-R" in console.perms %}
                    <a href="{% url 'authorization:show_permissions' team_pk=console.team.id %}">
                        <li class="console-navs {% if '/permissions/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-key"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Permissions</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "R-R" in console.perms or "C-R" in console.perms or "R-M" in console.perms or "U-M" in console.perms %}
                    <a href="{% url 'authorization:show_roles' team_pk=console.team.id %}">
                        <li class="console-navs {% if '/roles/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-layer-group"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Roles</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    <!-- {% if "U-T" in perms %} -->
                    <!-- <a href="">
                        <li class="console-navs {% if '/settings/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-gear"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Settings</p>
                            </div>
                        </li>
                    </a> -->
                    <!-- {% endif %} -->
                    {% if "R-JR" in console.perms or "C-JR" in console.perms or "U-JR" in console.perms or "D-JR" in console.perms %}
                    <a href="{% url 'team:join_requests' pk=console.team.id %}">
                        <li class="console-navs {% if '/join-requests/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-code-merge"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Join requests</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "E-TD" in console.perms %}
                    <a href="{% url 'team:get_todo_list' pk=console.team.id %}">
                        <li class="console-navs">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-list"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>To do list</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "V-FA" in console.perms %}
                    <a href="{% url 'team:view_analytics' pk=console.team.id %}">
                        <li class="console-navs {% if '/view-analytics/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-magnifying-glass-chart"></i>
                            </div>
                            <div class="console-nav-link">
                                <p>Feedback analytics</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                    {% if "D-T" in console.perms %}
                    <a href="#" onclick="showDeletePopup()">
                        <li class="console-navs {% if '/delete/' in request.path %}active-tab{% endif %}">
                            <div class="active-indicator">
                            </div>
                            <div class="console-nav-icon">
                                <i class="fa-solid fa-trash-can"></i>
                            </div>
                            <div class="console-nav-link text-red">
                                <p>Delete Team</p>
                            </div>
                        </li>
                    </a>
                    {% endif %}
                </ul>
            </nav>
        </aside>
    </div>
    <div id="delete-popup" class="hidden popup-container">
        <div  class="popup">
            <p class="text-[24px] font-semibold">Do you wish to delete the team?</p>
            <div class="mt-[10px] flex flex-row w-full space-x-5">
                <a href="{% url 'team:delete_team' pk=console.team.id %}"><button class="popup-yes">YES</button></a>
                <button class="popup-no" onclick="showDeletePopup()">NO</button>
            </div>
        </div>
    </div>
    <div id="leave-popup" class="hidden popup-container">
        <div  class="popup">
            <p class="text-[24px] font-semibold">Do you wish to leave the team?</p>
            <div class="mt-[10px] flex flex-row w-full space-x-5">
                <a href="{% url 'team:leave_team' pk=console.team.id %}"><button class="popup-yes">YES</button></a>
                <button class="popup-no" onclick="showLeavePopup()">NO</button>
            </div>
        </div>
    </div>
    <main class="flex grow mt-[10vh] mb-[10vh]">
        {% block workspace %}
        {% endblock %}
    </main>
</div>
{% endblock %}

sirius/templates/feedback_analytics.html
{% extends 'console.html' %}

{% load static %}

{% block workspace %}
<table>
<tr>
<td><center>
{{ data|safe }}
</center></td>
</tr>
<br>
<br>
<br> 
<tr>
<td><center>
{{ data1|safe }}
</center></td>
</tr>
</table>
{% endblock %}

sirius/templates/form.html
{% if form.non_field_errors %}
    <ul class="form-errors">
        {% for err in form.non_field_errors %}
            <li>{{ err }}</li>
        {% endfor %}
    </ul>
{% endif %}
<ul>
{% for field in form.visible_fields %}
<li>
    <p>
        {{ field.label_tag|cut:':' }}
    </p>
    {{ field }}
    {% if field.help_text %}
        <p class="field-help">
            {{ field.help_text }}
        </p>
    {% endif %}
    {% if field.errors %}
        <ul class="field-errors">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</li>
{% endfor %}
</ul>

sirius/templates/landing.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Welcome
{% endblock %}

{% block body %}
<body class="bg-[#ff9100] bg-opacity-40">
	<header class="h-[20vh] px-[8%]">
		<nav class="flex justify-between h-full items-end pb-12">
			<h5><a href="">College Club Management System</a></h5>
			<ul>
				<li class="btn-s text-[24px]"><a href="{% url 'user:signin' %}">Login</a></li>
			</ul>
		</nav>
	</header>
	<div class="bg-primary ms:h-[80vh] px-[8%] flex items-center">
		<main class="flex-col flex ms:flex-row ms:flex w-full justify-center ms:justify-between items-center space-y-[96px] py-12 ms:py-0">
			<div>
				<div class="w-[340px] md:w-[480px]">
					<h1>
						An easy to use platform to manage college clubs.
					</h1>
				</div>
				<a href="{% url 'user:signup' %}">
					<button class="btn-s text-[32px] mt-[10px]">Let's go</button>
				</a>
			</div>
			<img src="{% static 'images/monitor.svg' %}" class="mf:w-1/3 block w-[320px] ms:hidden mf:block">
			<div>
				<ul class="feature-list">
					<li>
						<i class="fa-solid fa-rocket"></i>
						<span>Fast</span>
					</li>
					<li>
						<i class="fa-solid fa-wind"></i>
						<span>Easy</span>
					</li>
					<li>
						<i class="fa-solid fa-shield"></i>
						<span>Secure</span>
					</li>
				</ul>
			</div>
		</main>
	</div>
</body>
{% endblock %}

sirius/templates/nav.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<body>
  <script>
    document.addEventListener('click', function(event) {
      const userConsoleToggler = document.getElementById('user-console-toggler');
      const userConsole = document.getElementById('user-console');
      if (userConsoleToggler.contains(event.target)) {
        userConsole.classList.toggle('hidden');
      } 
      else if (!userConsole.contains(event.target)) {
        userConsole.classList.add('hidden');
      }
    });
  </script>
  <header>
    <nav class="bg-primary text-white flex flex-row justify-between items-center px-[15%]">
      <ul class="py-4 space-x-10 flex items-center text-[22px]">
        <a href="{% url 'user:dashboard' u_pk=request.user.pk %}">
          <h5 class="cursor-pointer pb-3">College Club Management</h5>
        </a>
        <li class="cursor-pointer">About us</li>
        <a href="{% url 'team:create_team' %}">
          <li class="cursor-pointer">Start a Team</li>
        </a>
        <a href="{% url 'user:calendar' u_pk=request.user.pk %}">
          <li class="cursor-pointer">Calendar</li>
        <a href="{% url 'user:bulletin' %}">
          <li class="cursor-pointer">Bulletin</li>
        </a>
      </ul>
      <ul class="py-4 space-x-10 flex items-center text-[22px]">
        <li class="cursor-pointer text-[30px]"><i class="fa-solid fa-bell"></i></li>
        <li class="relative">
          <button type="button" id="user-console-toggler"><img
              src="{% static 'images/avatar.png' %}" id="user-avatar" /></button>
            <div id="user-console" class="hidden">
              <ul class="absolute flex flex-col justify-center items-center">
                <p class="text-[24px] font-semibold">{{ request.user.first_name }} {{ request.user.last_name }}</p>
                <p class="text-[18px] font-thin">{{ request.user.email }}</p>
                <div class="mt-[10px] flex flex-row w-full space-x-5">
                  <a href="{% url 'user:settings' %}"><i class="hover:scale-[1.2] fa-solid fa-gear"></i></a>
                  <a href="{% url 'user:signout' %}" id="logout-btn" class="text-primary"><button class="px-5  hover:bg-primary hover:text-white border-solid border-2 border-primary rounded-full"> Logout</button></a>
                </div>
              </ul>
            </div>
        </li>
      </ul>
    </nav>
  </header>
  <main class="flex px-[15%] pt-[2%] justify-center mf:justify-start">
    {% block main %}
    {% endblock %}
  </main>
</body>
{% endblock %}