sirius/sirius/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name='landing'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('user/', include('user.urls')),
    path('team/', include('team.urls')),
    # path('session/', include('session.urls')),
    path('authorization/<team_pk>/', include('authorization.urls'))
]

sirius/team/urls.py
from django.urls import path
from .views import *
from django.urls.conf import include

app_name = 'team'

urlpatterns = [
    path('create/', create_team, name='create_team'),
    path('<pk>/new-team/', create_sub_team, name='create_sub_team'),
    path('<pk>/info/', team_info, name='team_info'),
    path('<pk>/send-invite/<user>/', send_invite, name='send_invite'),
    path('send-join-request/', send_join_request, name='send_join_request'),
    path('<pk>/invites/', invites, name='invites'),
    path('<pk>/join-requests/', join_requests, name='join_requests'),
    path('accept-invite/<pk>/', accept_invite, name='accept_invite'),
    path('accept-join-request/<pk>/', accept_join_request, name='accept_join_request'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('decline-invite/<pk>/', decline_invite, name='decline_invite'),
    path('leave-team/<pk>/', leave_team, name='leave_team'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('<pk>/delete', delete_team, name='delete_team'),
    path('<pk>/get_todo_list', get_todo_list, name='get_todo_list'),
    path('<pk>/add_item', create_an_item, name='create_an_item'),
    path('<pk>/edit_item/<id>', edit_an_item, name='edit_an_item'),
    path('<pk>/toggle/<id>', toggle_status, name='toggle_status'),
    path('<pk>/view-analytics/', view_analytics, name='view_analytics'),
    path('<pk>/', include('session.urls', namespace="session"))
]

sirius/user/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from session.views import user_calendar, user_bulletin

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('settings/', views.accountsettings, name='settings'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('bulletin/', user_bulletin, name='bulletin'),
    path('<u_pk>/dashboard/', views.dashboard, name='dashboard'),
    path('<u_pk>/calendar/', user_calendar, name='calendar'),
    # path('<u_pk>/settings/', views.settings, name='settings'),
]

sirius/team/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid

class Team(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField()
    parent_id = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name

class JoinRequest(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
    )
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')

    def __str__(self):
        return self.user_id.email

class Invite(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
    )
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='invite_created_by')
    invited = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='invite_invited')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')

    def __str__(self):
        return self.user_id.username

class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)
    team_id = models.CharField(max_length=30, blank=False)
    def __str__(self):
        return self.name

sirius/user/models.py
from django.db import models

from django.core.validators import RegexValidator,MaxValueValidator,MinValueValidator
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    use_in_migrations = True
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        if not password:
            raise ValueError('Users must have an password address')
        email = self.normalize_email(email)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user


    def create_superuser(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

class CustomUser(AbstractUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('NB','Non-Binary')
    )
    gender = models.CharField(_('gender'), max_length=2, choices=GENDER_CHOICES)
    email = models.EmailField(_('email address'), unique=True)
    is_superuser = models.BooleanField(_('superuser status'),default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = CustomUserManager()

    def __str__(self):
        return self.email

sirius/user/forms.py
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class AccountSignupForm(UserCreationForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput)
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
            'gender',
        ]

class AccountAuthenticationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    class Meta:
        model = get_user_model()
        fields = [
            'email',
            'password',
        ]
    def clean(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        if not authenticate(email=email, password=password):
            raise forms.ValidationError("Invalid login credentials!")

# class AccountUpdateForm(forms.ModelForm):
#     class Meta:
#         model = get_user_model()
#         fields = [
#             'first_name',
#             'last_name',
#         ]
#     def clean_email(self):
#         email = self.cleaned_data['email']
#         try:
#             get_user_model().objects.exclude(pk=self.instance.pk).get(email=email)
#         except get_user_model().DoesNotExist:
#             return email
#         raise forms.ValidationError('Email "%s" is already in use.' % email)

class ResetPasswordForm(forms.ModelForm):
    first_name = forms.CharField(label="First name", widget=forms.TextInput)
    last_name = forms.CharField(label="Last name", widget=forms.TextInput, required=False)
    email = forms.EmailField(label="Email address", widget=forms.TextInput, disabled=True, required=False)
    username = forms.CharField(label="Username", widget=forms.TextInput, disabled=True, required=False)
    old_password = forms.CharField(label="Old password", widget=forms.PasswordInput)
    new_password1 = forms.CharField(label="New password", widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Confirm password", widget=forms.PasswordInput)


    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
            'username',
        ]

    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Old password is incorrect!")
        
    def clean_new_password2(self):
        new_password1 = self.cleaned_data['new_password1']
        new_password2 = self.cleaned_data['new_password2']
        if new_password1 != new_password2:
            raise forms.ValidationError("Passwords do not match!")
        print(validate_password(new_password2))
        return self.cleaned_data

sirius/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from .forms import AccountAuthenticationForm, AccountSignupForm, ResetPasswordForm
from authorization.models import Membership
from team.models import JoinRequest
from team.forms import JoinRequestForm

def signup(request):
    if request.user.is_authenticated:
        return redirect('user:dashboard', u_pk=request.user.pk)
    if request.method == 'POST':
        form = AccountSignupForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('user:dashboard', u_pk=request.user.pk)
        else:
            return render(request, 'signup.html', {'form': form})
    else:
        form = AccountSignupForm()
        return render(request, 'signup.html', {'form': form})

def signin(request):
    user = request.user
    if user.is_authenticated:
        return redirect('user:dashboard', u_pk=request.user.pk)
    if request.method == 'POST':
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('user:dashboard', u_pk=request.user.pk)
        else:
            return render(request, 'signin.html', {'form': form})
    else:
        form = AccountAuthenticationForm()
    return render(request, 'signin.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('landing')

# def dashboard_view(request, user_id, join_form=None):
#     user = get_user_model().objects.values('email', 'first_name', 'last_name').get(pk=user_id)
#     teams = Membership.objects.filter(user_id=user_id).values('created_at', 'alumni', 'team_id__pk', 'team_id__name', 'role_id__pk', 'role_id__role_name')
#     join_requests = JoinRequest.objects.filter(user_id=user_id)
#     if not join_form:
#         join_form = JoinRequestForm()
#     return render(request, 'dashboard.html', {
#         'user': user, 
#         'teams': teams,
#         'join_requests': join_requests,
#         'join_form': join_form
#     })

@login_required(login_url='user:signin')
def dashboard(request, u_pk):
    user = get_user_model().objects.values('email', 'first_name', 'last_name').get(pk=u_pk)
    teams = Membership.objects.filter(user_id=u_pk).values('created_at', 'alumni', 'team_id__id', 'team_id__name', 'role_id__pk', 'role_id__role_name')
    join_requests = JoinRequest.objects.filter(user_id=u_pk)
    join_form = JoinRequestForm()
    join_form_errors = request.session.get('join_form_errors')
    if join_form_errors:
        for field, err in join_form_errors.items():
            join_form.errors[field] = err
        del request.session['join_form_errors']
    return render(request, 'dashboard.html', {
        'user': user, 
        'teams': teams,
        'join_requests': join_requests,
        'join_form': join_form
    })

@login_required(login_url='user:signin')
def accountsettings(request):
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST, instance=request.user)
        if form.is_valid():
            user = request.user
            user.set_password(form.cleaned_data.get('new_password1'))
            user.save()
            return redirect('user:dashboard', u_pk=request.user.pk)
        else:
            return render(request, 'settings.html', {'form': form})
    else:
        form = ResetPasswordForm(instance=request.user)
        return render(request, 'settings.html', {'form': form})

# @login_required(login_url='user:signin')
# def accountchange(request):
#     user = get_user_model().objects.values('email', 'first_name', 'last_name').get(pk=request.user.pk)
#     if user.check_password(request.POST['password']):
#         user.first_name = request.POST.get('first_name')
#         user.last_name = request.POST.get('last_name')
#         user.set_password(request.POST['new_password'])
#         user.save()
#         return redirect('user:dashboard', u_pk=request.user.pk)
#     else:
#         return render(request, 'settings.html', {'user': user, 'error': 'Incorrect password'})

sirius/user/templates/dashboard.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}
    Dashboard
{% endblock %}

{% block links %}
    <script src="{% static 'js/send_join_request.js' %}"></script>
{% endblock %}

{% block main %}
    <script>
        document.addEventListener('DOMContentLoaded', (e) => {
            const reqs = Array.prototype.slice.call(document.getElementsByClassName('req-status'));
            console.log(reqs)
            for (let req of reqs) {
                const id = req.id.replace('status', 'badge');
                const badge = document.getElementById(id);
                const status = req.innerHTML;
                if(status == 'Pending') {
                    badge.classList.add('bg-yellow')
                } else if (status == 'Accepted') {
                    badge.classList.add('bg-green');
                } else if (status == 'Rejected') {
                    badge.classList.add('bg-red');
                }
            }
        })
    </script>
    <div class="flex flex-col mf:flex-row w-full">
        <section class="w-full mf:w-[90%] flex flex-col items-center mf:items-start">
            <h3 class="mb-[2%]">Yours Teams</h3>
            <ul class="flex flex-col justify-center">
                <div class="flex flex-wrap justify-center mf:justify-start gap-[35px]">
                    {% for team in teams %}
                    <li class="hover:scale-[1.05] flex flex-col items-center h-[250px] justify-between pb-2 bg-white shadow rounded-lg w-[250px] overflow-clip"><a href="{% url 'team:team_info' pk=team.team_id__id %}">
                            <div class="h-[190px] overflow-clip mb-[6px]">
                                <img class="w-full" src="https://picsum.photos/300/300?random={{ team.team_id__id }}"/>
                            </div>
                            <p class="text-grey font-400 text-[32px] text-center">{{ team.team_id__name|truncatechars:8 }}<span class="text-[18px]">#{{ team.team_id__id|truncatechars:5 }}</span></p>
                    </a></li>
                    {% endfor %}
                </div>
            </ul>
        </section>
        <div class="mb-[10vh] flex flex-col items-center pt-[75px]">
            <section class="form-wrapper small-console mt-0 h-fit">
                <h4>Send a Request</h4>
                <form method="POST" action="{% url 'team:send_join_request' %}">
                    {% csrf_token %}
                    {% include 'form.html' with form=join_form %}
                    <input type="hidden" name="user_id" value="{{ request.user.pk }}">
                    <input type="submit" value="Join" class="mb-0">
                </form>
            </section>
            <section class="small-console mt-[35px]">
                <h4>Join Requests</h4>
                <ul class="w-full pl-[16px] max-h-[240px] overflow-y-scroll mt-[16px] flex flex-col space-y-[10px]">
                    {% for req in join_requests %}
                        <li class="flex items-center">
                            <span class="inline-block h-[50px] w-[24px] mr-[16px]" id="req-badge-{{ req.pk }}"></span>
                            <span class="font-poppins text-[24px] text-grey tracking-[0.06rem] font-[500] min-w-[160px]">{{ req.team_id|truncatechars:6 }}</span>
                            <span class="inline-block ml-[16px] text-grey font-[300] italic text-[18px] req-status" id="req-status-{{ req.pk }}">{{ req.get_status_display }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        </div>
    </div>
{% endblock %}

sirius/user/templates/settings.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}
    {{ request.user.username }}
{% endblock %}
    
{% block main %}
<div class="w-full flex flex-wrap-reverse lg:flex-row lg:flex-nowrap justify-center mt-[4vh] gap-y-[2vh]">
    <div class="items-center hidden mf:flex">
        <img src="{% static 'images/tools.png' %}" class="h-fit w-[560px]" />
    </div>
    <div class="form-wrapper flex items-center w-full">
        <div>
            <h2>Account</h2>
            <form method="POST" action="{% url 'user:settings' %}">
                {% csrf_token %}
                {% include 'form.html' with form=form %}
                <input type="submit" value="Save" class="!w-[180px] mx-auto !bg-green">
            </form>
        </div>
    </div>
    <div class="flex items-center">
        <div class="w-[300px] h-[300px] rounded-[150px] overflow-clip">
            <img src="{% static 'images/avatar.png' %}" class="h-fit" />
        </div>
    </div>
</div>
{% endblock %}

sirius/user/templates/signin.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block body %}

<body>
    <div class="flex flex-row h-[100vh]">
        <div class="form-wrapper mt-[10vh]">
            <div>
                <header>
                    <a href="{% url 'landing' %}"><h5 class="text-primary">College Club System</h5></a>
                    <h6>New to the platform? <a href="{% url 'user:signup' %}"><span class="text-blue">Signup</span></a></h6>
                    <h2>Login</h2>
                </header>
                <form method="POST" action="{% url 'user:signin' %}">
                    {% csrf_token %}
                    {% include 'form.html' with form=form %}
                    <input id="grid-first-name"  type="submit" value="Login">
                    {% if request.GET.next %}
                    <input type="hidden" name="text" value="{{ request.GET.next }}">
                    {% endif %}
                    <section>
                        <p class="flex justify-center">Or signup with</p>
                        <ul class="flex justify-around flex-row text-[45px] py-[4%]">
                            <li><i class="fa-brands fa-google"></i></li>
                            <li><i class="fa-brands fa-facebook-f"></i></li>
                            <li><i class="fa-brands fa-github"></i></li>
                        </ul>
                    </section>
                </form>
            </div>
        </div>
        <div class="grow bg-primary hidden md:flex md:w-1/2 justify-center items-center px-[5%]">
            <blockquote>
                <div>
                    <i class="fa-solid fa-quote-left"></i>
                </div>
                <cite>Oscar Wilde</cite>
                <p>Be yourself; everyone else is already taken.</p>
            </blockquote>
        </div>
    </div>
</body>
{% endblock %}

sirius/user/templates/signup.html
{% extends 'base.html' %}

{% block title %}
    Signup
{% endblock %}

{% block body %}

<body>
    <div class="flex flex-row">
        <div class="form-wrapper mt-[10vh] mb-[10vh]">
            <div>
                <header>
                    <a href="{% url 'landing' %}">
                        <h5 class="text-primary">College Club System</h5>
                    </a>
                    <h6>Have an account? <a href="{% url 'user:signin' %}"><span class="text-blue">Login</span></a></h6>
                    <h2>Signup</h2>
                </header>
                <form method="POST" action="{% url 'user:signup' %}">
                    {% csrf_token %}
                    {% include 'form.html' with form=form %}
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
        <div class="grow bg-primary hidden md:flex md:w-1/2 justify-center items-center px-[5%]">
            <blockquote>
                <div>
                    <i class="fa-solid fa-quote-left"></i>
                </div>
                <cite>13 Hours</cite>
                <p>All the gods, all the heavens, all the hells are within you.</p>
            </blockquote>
        </div>
    </div>
</body>
{% endblock %}