sirius/authorization/urls.py
from django.urls import path
from .views import *

app_name = 'authorization'

urlpatterns = [
    path('role/create/', create_role, name='create_role'),
    path('roles/', show_roles, name='show_roles'),
    path('roles/update/', update_roles, name='update_roles'),
    path('permissions/', show_permissions, name='show_permissions'),
    path('permissions/update/', update_permissions, name='update_permissions'),
    path('role/<r_pk>/delete/', delete_role, name='delete_role'),
    path('role/<r_pk>/update/', update_role, name='update_role'),

]

sirius/sirius/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name='landing'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('user/', include('user.urls')),
    path('team/', include('team.urls')),
    # path('session/', include('session.urls')),
    path('authorization/<team_pk>/', include('authorization.urls'))
]

sirius/team/urls.py
from django.urls import path
from .views import *
from django.urls.conf import include

app_name = 'team'

urlpatterns = [
    path('create/', create_team, name='create_team'),
    path('<pk>/new-team/', create_sub_team, name='create_sub_team'),
    path('<pk>/info/', team_info, name='team_info'),
    path('<pk>/send-invite/<user>/', send_invite, name='send_invite'),
    path('send-join-request/', send_join_request, name='send_join_request'),
    path('<pk>/invites/', invites, name='invites'),
    path('<pk>/join-requests/', join_requests, name='join_requests'),
    path('accept-invite/<pk>/', accept_invite, name='accept_invite'),
    path('accept-join-request/<pk>/', accept_join_request, name='accept_join_request'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('decline-invite/<pk>/', decline_invite, name='decline_invite'),
    path('leave-team/<pk>/', leave_team, name='leave_team'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('<pk>/delete', delete_team, name='delete_team'),
    path('<pk>/get_todo_list', get_todo_list, name='get_todo_list'),
    path('<pk>/add_item', create_an_item, name='create_an_item'),
    path('<pk>/edit_item/<id>', edit_an_item, name='edit_an_item'),
    path('<pk>/toggle/<id>', toggle_status, name='toggle_status'),
    path('<pk>/view-analytics/', view_analytics, name='view_analytics'),
    path('<pk>/', include('session.urls', namespace="session"))
]

sirius/authorization/models.py
from django.db import models
from team.models import Team
from django.contrib.auth import get_user_model

class Role(models.Model):
    role_name = models.CharField(max_length=100)
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    role_description = models.CharField(max_length=100)
    permissions = models.TextField(default="")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['role_name', 'team_id'], 
                name='unique_role_name_team_id'
            )
        ]

    def __str__(self):
        return self.role_name

class Membership(models.Model):
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    alumni = models.BooleanField(default=False)
    role_id = models.ForeignKey(Role, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user_id', 'team_id'], 
                name='unique_user_id_team_id'
            )
        ]

    def __str__(self):
        return f'{self.user_id.username}-{self.team_id.name}'
        
class Permission(models.Model):
    ACTION_CHOICES = (
        ('C', 'Create'),
        ('R', 'Read'),
        ('U', 'Update'),
        ('D', 'Delete'),
        ('E', 'Edit'),
        ('V', 'View'),
    )
    RELATION_CHOICES = (
        ('T', 'Team'),
        ('R', 'Role'),
        ('C', 'Class'),
        ('N', 'Notice'),
        ('E', 'Event'),
        ('P', 'Project'),
        ('M', 'Membership'),
        ('JR', 'JoinRequest'),
        ('I', 'Invite'),
        ('TD', 'ToDo'),
        ('FA', 'FeedbackAnalysis'),
    )
    action = models.CharField("action", max_length=1, choices= ACTION_CHOICES)
    relation = models.CharField("relation", max_length=2, choices= RELATION_CHOICES)

    def __str__(self):
        return self.action + " " + self.relation

sirius/authorization/forms.py
from django import forms
from .models import Role,Membership
from team.models import Team

class RoleCreationForm(forms.ModelForm):
    class Meta:
        widgets = {
            'team_id': forms.HiddenInput(),
        }
        model = Role
        fields = ('role_name', 'team_id')

    # def clean_team_id(self):
    #     team_id = self.cleaned_data.get('team_id')
    #     if not Team.objects.filter(id=team_id).exists():
    #         raise forms.ValidationError('Invalid Team id')
    #     team = Team.objects.get(id=team_id)
    #     return team

class MembershipUpdationForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ('user_id', 'role_id')

sirius/authorization/views.py
from django.shortcuts import render,redirect
from .forms import RoleCreationForm
from django.contrib.auth.decorators import login_required
from .models import Role
from authorization.models import Membership, Permission
from team.models import Team
from sirius.utils.perm import has_perm, display_perms
from django.http import Http404, HttpResponse, HttpResponseForbidden, HttpResponseBadRequest
from sirius.utils.console_context import get_console_data

@login_required(login_url='user:signin')
def create_role(request, team_pk):
    if request.method == 'POST':
        if not has_perm('C', 'R', request.user, team_pk):
            return HttpResponseForbidden()
        form = RoleCreationForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            request.session['create_role_errors'] = form.errors
        return redirect('authorization:show_roles', team_pk)
    return Http404()
        
@login_required(login_url='user:signin')
def show_roles(request, team_pk):
    members = Membership.objects.filter(team_id=team_pk).values('pk', 'user_id__pk', 'user_id__first_name', 'user_id__last_name', 'user_id__email', 'role_id__role_name', 'role_id__role_description', 'role_id__pk')
    roles = Role.objects.filter(team_id=team_pk).values('pk', 'role_name', 'role_description')
    role_form = RoleCreationForm()
    create_role_errors = request.session.get('create_role_errors')
    if create_role_errors:
        for field, err in create_role_errors.items():
            role_form.errors[field] = err
        del request.session['create_role_errors']
    return render(request, 'show_roles.html', {
        'members': members,
        'roles': roles,
        'console': get_console_data(team_pk, request.user),
        'role_form': role_form
    })


@login_required(login_url='user:signin')
def update_roles(request, team_pk):
    if request.method == 'POST':
        if not has_perm('U', 'R', request.user, team_pk):
            return HttpResponseForbidden()
        for key, role_id in request.POST.items():
            if key.startswith('role-'):
                member_pk = key.split('-')[1]
                membership = Membership.objects.get(pk=member_pk)
                membership.role_id = Role.objects.get(pk=role_id)
                membership.save()
        return redirect('authorization:show_roles', team_pk=team_pk)
    return Http404()


@login_required(login_url='user:signin')
def show_permissions(request, team_pk):
    if not has_perm('R', 'R', request.user, team_pk):
        return HttpResponseForbidden()
    roles = Role.objects.filter(team_id__id=team_pk).values('pk', 'role_name', 'role_description', 'permissions')
    all_permissions = Permission.objects.all()
    return render(request, 'show_permissions.html', {
        'console': get_console_data(team_pk, request.user),
        'roles': roles,
        'all_permissions': all_permissions,
        'role_based_perms': display_perms(roles)
    })

@login_required(login_url='user:signin')
def update_permissions(request, team_pk):
    if request.method == 'POST':
        if not has_perm('U', 'R', request.user, team_pk):
            return HttpResponseForbidden()
        role_pk = request.POST['role-pk']
        perm_string = request.POST['perm-string']
        if not perm_string or not role_pk:
            return HttpResponseBadRequest('Invalid request')
        role = Role.objects.get(pk=role_pk)
        if not role:
            return HttpResponseBadRequest('Invalid request')
        if str(role.team_id.id) != str(team_pk):
            return HttpResponseBadRequest('Invalid request')
        role.permissions = perm_string
        role.save()
        return redirect('authorization:show_permissions', team_pk=team_pk)
    return Http404()

@login_required(login_url='user:signin')
def delete_role(request, team_pk, r_pk):
    if not has_perm('D', 'R', request.user, team_pk):
        return HttpResponseForbidden()
    role = Role.objects.get(pk=r_pk)
    if str(role.team_id.id) != str(team_pk):
        return HttpResponseBadRequest('Invalid request')
    if not role:
        return HttpResponseBadRequest('Invalid request')
    if role.role_name == "Admin" or role.role_name == "Member":
        return HttpResponseBadRequest(f'Cannot delete {role.role_name} role')
    curr_members = Membership.objects.filter(team_id__id=team_pk).filter(role_id__pk=r_pk)
    member_role = Role.objects.get(team_id__id=team_pk, role_name = "Member")
    for member in curr_members:
        member.role_id = member_role
        member.save()
    role.delete()
    return redirect('authorization:show_roles', team_pk=team_pk)

@login_required(login_url='user:signin')
def update_role(request, team_pk, r_pk):
    if request.method == 'POST':
        if not has_perm('U', 'R', request.user, team_pk):
            return HttpResponseForbidden()
        role = Role.objects.get(pk=r_pk)
        if str(role.team_id.id) != str(team_pk):
            return HttpResponseBadRequest('Invalid request')
        if not role:
            return HttpResponseBadRequest('Invalid request')
        form = RoleCreationForm(request.POST, instance=role)
        if form.is_valid():
            form.save()
        else:
            request.session['update_role_errors'] = form.errors
        return redirect('authorization:show_roles', team_pk=team_pk)
    return Http404()

sirius/authorization/templates/show_permissions.html
{% extends 'console.html' %}

{% block script %}
    let currRole;
    let roleIn;
    let roleOut;
    let addHint;
    let removeHint;
    let roleIdInput;
    let permStringInput;
    let rolePerm;
    let allPermissions = [];
    let submitButton;
    let roleDict = {{ role_based_perms }};
    document.addEventListener('DOMContentLoaded', function() {
        currRole = {{ roles.first.pk }};
        roleIn = document.getElementById('role-in');
        addHint = document.getElementById('add-hint');
        removeHint = document.getElementById('remove-hint');
        roleIdInput = document.getElementById('role-pk-in');
        permStringInput = document.getElementById('perm-string-in');
        roleOut = document.getElementById('role-out');
        submitButton = document.getElementById('upt-form-submit')
        {% for perm in all_permissions %}
            allPermissions.push({
                'pk': {{ perm.pk }},
                'action': "{{ perm.get_action_display }}",
                'relation': "{{ perm.get_relation_display }}"
            });
        {% endfor %}
        fillRoles();
    });
    function fillRoles() {
        roleIn.innerHTML = '';
        roleOut.innerHTML = '';
        rolePerm = roleDict[currRole];
        allPermissions.forEach((perm) => {
            const li = document.createElement('li');
            li.classList.add('perm-tile')
            li.innerHTML = `${perm.action} ${perm.relation}`;
            li.id = `perm-${perm.pk}`;
            if (rolePerm.includes(perm['pk'])) {
                removeHint.classList.remove('hidden');
                li.classList.add('bg-light-blue');
                {% if "U-R" in console.perms %}
                li.onclick = () => { toggleDeleteStatus(`perm-${perm['pk']}`); }
                {% endif %}
                roleIn.appendChild(li);

            }
            else {
                addHint.classList.remove('hidden');
                li.classList.add('bg-grey/10');
                {% if "U-R" in console.perms %}
                li.onclick = () => { toggleAddStatus(`perm-${perm['pk']}`); }
                {% endif %}
                roleOut.appendChild(li);
            }
        });
    }
    function changeCurrRole(newRole) {
        currRole = newRole;
        addHint.classList.add('hidden');
        addHint.classList.add('hidden');
        fillRoles();
    }
    function toggleDeleteStatus(permId) {
        const perm = document.getElementById(permId);
        perm.classList.toggle('!bg-red/70');
        perm.classList.toggle('!text-white');
    }
    function toggleAddStatus(permId) {
        const perm = document.getElementById(permId);
        perm.classList.toggle('!bg-green/70');
        perm.classList.toggle('!text-white');
    }
    function saveSelection() {
        roleIn.childNodes.forEach((li) => {
            if (li.classList.contains('!bg-red/70')) {
                const index = rolePerm.indexOf(Number(li.id.split('-')[1]));
                if (index > -1) {
                    rolePerm.splice(index, 1);
                }
            }
        });
        roleOut.childNodes.forEach((li) => {
            if (li.classList.contains('!bg-green/70')) {
                rolePerm.push(Number(li.id.split('-')[1]));
            }
        });
        
        let permString = rolePerm.join(',') + ',';
        
        roleIdInput.value = currRole;
        permStringInput.value = permString;
        submitButton.click();
    }
{% endblock %}


{% block workspace %}
    <div class="">
        <div class="flex flex-row">
        <select onchange="changeCurrRole(this.value)" class="text-[24px] font-medium w-[240px] py-[16px] rounded-md" default="{{ roles.first.pk }}">
            {% for role in roles %}
                <option value="{{ role.pk }}">{{ role.role_name }}</option>
            {% endfor %}
        </select>
      
      </div>

        <div>
            {% if "U-R" in console.perms %}
            <p class="italic text-grey my-[8px] hidden" id="remove-hint">Click on tiles to remove privileges</p>
            {% else %}
            <p class="italic text-grey my-[8px] hidden" id="remove-hint">Current permissions</p>
            {% endif %}
            <ul id="role-in" class="perm-list"></ul>
            {% if "U-R" in console.perms %}
                <p class="italic text-grey my-[8px] hidden" id="add-hint">Click on tiles to add privileges</p>
            {% else %}
                <p class="italic text-grey my-[8px] hidden" id="add-hint">Available permissions</p>
            {% endif %}
            <ul id="role-out" class="perm-list"></ul>
            {% if "U-R" in console.perms %}
            <button class="save-btn" onclick="saveSelection()">Save</button>
            {% endif %}
        </div>
        {% if "U-R" in console.perms %}
        <form class="hidden" method="POST" action="{% url 'authorization:update_permissions' team_pk=console.team.id %}">
            {% csrf_token %}
            <input name="role-pk" id="role-pk-in" />
            <input name="perm-string" id="perm-string-in" />
            <input type="submit" value="Go" id="upt-form-submit" />
        </form>
        {% endif %}
    </div>
{% endblock %}

sirius/authorization/templates/show_roles.html
{% extends 'console.html' %} 

{% block workspace %}
<div class="flex lf:flex-row flex-col w-full items-center lf:justify-between lf:items-start lf:pl-[10%] gap-y-[10vh]">
  <section>
    <ul>
      <form method="POST" action="{% url 'authorization:update_roles' team_pk=console.team.id %}">
        {% csrf_token %}
        {% for member in members %}
          <li class="member-card">
            <div>
                <p class="member-name">{{ member.user_id__first_name }} {{ member.user_id__last_name }}</p>
                <p class="member-username">@{{ member.user_id__username }}</p>
            </div>
            <select name="role-{{ member.pk }}" class="rounded-md member-role w-[120px]" {% if "U-M" not in console.perms %}disabled{% endif %}>
              {% for role in roles %}
                  {% if role.role_name == member.role_id__role_name %}
                      <option value="{{ role.pk }}" selected>{{ role.role_name }}</option>
                  {% else %}
                      <option value="{{ role.pk }}">{{ role.role_name }}</option>
                  {% endif %}
              {% endfor %}
            </select>
          </li>
        {% endfor %}
        {% if "U-M" in console.perms %}
        <input type="submit" value="Save" class="save-btn" />
        {% endif %}
      </form>
    </ul>
  </section>
  <div class="mb-[10vh] flex flex-col items-center">
    {% if "C-R" in console.perms %}
    <section class="form-wrapper small-console mt-0 h-fit">
      <h4>Create a Role</h4>
      <form method="POST" action="{% url 'authorization:create_role' team_pk=console.team.id %}">
          {% csrf_token %}
          {% include 'form.html' with form=role_form %}
          <input type="hidden" name="team_id" value="{{ console.team.id }}">
          <input type="submit" value="Create">
      </form>
    </section>
    {% endif %}
    <section class="small-console mt-[35px]">
        <h4>Roles</h4>
        <ul class="w-full mt-[16px] flex flex-col space-y-[10px]">
            {% for role in roles %}
                <li class="flex items-center w-full justify-between px-[32px]">
                    <span class="font-poppins text-[24px] text-grey tracking-[0.06rem] font-[500] min-w-[160px] {% if role.role_name|length > 9 %}cursor-help{% endif %}" {% if role.role_name|length > 10 %}title="{{ role.role_name }}"{% endif %}>{{ role.role_name|truncatechars:9 }}</span>
                    <div class="role-control invisible {% if 'D-R' in console.perms and role.role_name != 'Admin' and role.role_name != 'Member' %}!visible{% endif %}">
                        <a href="{% url 'authorization:delete_role' r_pk=role.pk team_pk=console.team.id %}"><i class="fa-solid fa-trash-can text-red"></i></a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
  </div>
</div>
{% endblock %}