sirius/sirius/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name='landing'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('user/', include('user.urls')),
    path('team/', include('team.urls')),
    # path('session/', include('session.urls')),
    path('authorization/<team_pk>/', include('authorization.urls'))
]

sirius/team/urls.py
from django.urls import path
from .views import *
from django.urls.conf import include

app_name = 'team'

urlpatterns = [
    path('create/', create_team, name='create_team'),
    path('<pk>/new-team/', create_sub_team, name='create_sub_team'),
    path('<pk>/info/', team_info, name='team_info'),
    path('<pk>/send-invite/<user>/', send_invite, name='send_invite'),
    path('send-join-request/', send_join_request, name='send_join_request'),
    path('<pk>/invites/', invites, name='invites'),
    path('<pk>/join-requests/', join_requests, name='join_requests'),
    path('accept-invite/<pk>/', accept_invite, name='accept_invite'),
    path('accept-join-request/<pk>/', accept_join_request, name='accept_join_request'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('decline-invite/<pk>/', decline_invite, name='decline_invite'),
    path('leave-team/<pk>/', leave_team, name='leave_team'),
    path('decline-join-request/<pk>/', decline_join_request, name='decline_join_request'),
    path('<pk>/delete', delete_team, name='delete_team'),
    path('<pk>/get_todo_list', get_todo_list, name='get_todo_list'),
    path('<pk>/add_item', create_an_item, name='create_an_item'),
    path('<pk>/edit_item/<id>', edit_an_item, name='edit_an_item'),
    path('<pk>/toggle/<id>', toggle_status, name='toggle_status'),
    path('<pk>/view-analytics/', view_analytics, name='view_analytics'),
    path('<pk>/', include('session.urls', namespace="session"))
]

sirius/team/models.py
from django.db import models
from django.contrib.auth import get_user_model
import uuid

class Team(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    description = models.TextField()
    parent_id = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name

class JoinRequest(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
    )
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')

    def __str__(self):
        return self.user_id.email

class Invite(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
    )
    team_id = models.ForeignKey(Team, on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='invite_created_by')
    invited = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='invite_invited')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')

    def __str__(self):
        return self.user_id.username

class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)
    team_id = models.CharField(max_length=30, blank=False)
    def __str__(self):
        return self.name

sirius/team/forms.py
from django import forms
from .models import Team, JoinRequest, Item
from authorization.models import Membership

class TeamCreationForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ('name',)
    # def clean(self):
    #     name = self.cleaned_data.get('name')
        # parent_id = self.cleaned_data.get('parent_id')
        # if parent_id is not None:
        #     if Team.objects.filter(id=parent_id).count() == 0:
        #         raise forms.ValidationError('Parent team does not exist')

class MembershipCreationForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ('team_id', 'user_id', 'alumni', 'role_id')
    def clean(self):
        team_id = self.cleaned_data.get('team_id')
        user_id = self.cleaned_data.get('user_id')
        if Membership.objects.filter(team_id=team_id, user_id=user_id).count():
            raise forms.ValidationError('User is already a member of this team')

class JoinRequestForm(forms.ModelForm):
    team_id = forms.CharField()
    class Meta:
        widgets = {
            'user_id': forms.HiddenInput(),
        }
        model = JoinRequest
        fields = ('team_id','user_id')

    def clean_team_id(self):
        team_id = self.cleaned_data.get('team_id')
        if not Team.objects.filter(id=team_id).exists():
            raise forms.ValidationError('Invalid id')
        team = Team.objects.get(id=team_id)
        return team
    
    def clean(self):
        team_id = self.cleaned_data.get('team_id')
        user_id = self.cleaned_data.get('user_id')
        if Membership.objects.filter(team_id=team_id, user_id=user_id).count():
            raise forms.ValidationError('You are already a member of this team')
        if JoinRequest.objects.filter(status='P', team_id=team_id, user_id=user_id).exists():
            raise forms.ValidationError('A request is already pending')

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'done')
        

        

sirius/team/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from team.models import Team, JoinRequest, Invite, Item
from .forms import TeamCreationForm, JoinRequestForm, ItemForm
from authorization.models import Membership, Permission, Role
from session.models import Feedback, Session
from sirius.utils.perm import get_perms, has_perm
from sirius.utils.console_context import get_console_data
from .utils import init_roles
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
from io import StringIO
from wordcloud import WordCloud, STOPWORDS

@login_required(login_url='user:signin')
def create_team(request):
    if request.method == 'POST':
        form = TeamCreationForm(request.POST)
        if form.is_valid():
            team = form.save(commit=False)
            team.save()
            init_roles(team, request.user)
            return redirect('team:team_info', pk=form.instance.id)
    else:
        form = TeamCreationForm()
    return render(request, 'new_team.html', {'form': form})

@login_required(login_url='user:signin')
def create_sub_team(request, pk):
    if request.method == 'POST':
        form = TeamCreationForm(request.POST)
        if form.is_valid():
            if form.cleaned_data.get('parent_id'):
                if not has_perm('C', 'T', request.user, form.cleaned_data.get('parent_id')):
                    return HttpResponseForbidden()
            team = form.save(commit=False)
            if Team.objects.filter(id=pk).count() == 0:
                raise form.ValidationError("Parent team does not exist")
            if not has_perm('C', 'T', request.user, pk):
                return HttpResponseForbidden()
            else:
                parent = Team.objects.get(id=pk)
                team.parent_id = parent
            team.save()
            init_roles(team, request.user)
            return redirect('team:team_info', pk=form.instance.pk)
    else:
        form = TeamCreationForm()
    return render(request, 'create_sub_team.html', {'form': form, 'console': get_console_data(pk, request.user)})

@login_required(login_url='user:signin')
def team_info(request, pk):
    members = Membership.objects.filter(team_id=pk).values('created_at', 'alumni', 'user_id__pk', 'user_id__first_name', 'user_id__last_name', 'user_id__username', 'role_id__pk', 'role_id__role_name')
    children = Team.objects.filter(parent_id=pk).values('name', 'id')
    return render(request, 'team_info.html', {
        'members': members,
        'children': children,
        'console': get_console_data(pk, request.user)
    })

@login_required(login_url='user:signin')
def send_invite(request, pk, user):
    if request.method == 'POST':
        if not has_perm('C', 'I', request.user, pk):
            return HttpResponseForbidden()
        if Invite.objects.filter(status = 'P', team_id=pk, invited=user).exists():
            return redirect('team:team_info', pk=pk)
        invite = Invite(team_id=Team.objects.get(id=pk), created_by=request.user, invited=get_user_model().objects.get(pk=user))
        invite.save()
        return redirect('team:team_info', pk=pk)
    return redirect('team:team_info', pk=pk)

@login_required(login_url='user:signin')
def send_join_request(request):
    if request.method == 'POST':
        form = JoinRequestForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            request.session['join_form_errors'] = form.errors
    return redirect('user:dashboard', u_pk=request.user.pk)

@login_required(login_url='user:signin')
def invites(request, pk):
    if not has_perm('R', 'I', request.user, pk):
        return HttpResponseForbidden()
    invites = Invite.objects.filter(team_id=pk, status='P').values('invited__first_name', 'invited__last_name', 'invited__email', 'invited__pk', 'created_at', 'status', 'pk', 'created_by__first_name', 'created_by__last_name', 'created_by__email', 'created_by__pk')
    return render(request, 'invites.html', {'invites': invites, 'console': get_console_data(pk, request.user)})

@login_required(login_url='user:signin')
def join_requests(request, pk):
    if not has_perm('R', 'JR', request.user, pk):
        return HttpResponseForbidden()
    requests = JoinRequest.objects.filter(team_id=pk, status='P').values('user_id__first_name', 'user_id__last_name', 'user_id__username', 'user_id__pk', 'created_at', 'status', 'pk')
    return render(request, 'join_requests.html', {'requests': requests, 'console': get_console_data(pk, request.user)})

@login_required(login_url='user:signin')
def accept_invite(request, pk):
    if request.method == 'POST':
        invite = Invite.objects.get(pk=pk)
        if not has_perm('U', 'I', request.user, invite.team_id.id):
            return HttpResponseForbidden()
        invite.status = 'A'
        invite.save()
        membership = Membership(team_id=invite.team_id, user_id=invite.invited)
        membership.save()
        return redirect('team:team_info', pk=invite.team_id.id)

@login_required(login_url='user:signin')
def accept_join_request(request, pk):
    if request.method == 'POST':
        join_request = JoinRequest.objects.get(pk=pk)
        if not has_perm('U', 'JR', request.user, join_request.team_id.id):
            return HttpResponseForbidden()
        join_request.status = 'A'
        join_request.save()
        membership = Membership.objects.filter(team_id=join_request.team_id, user_id=join_request.user_id).first()
        if not membership:
            membership = Membership(team_id=join_request.team_id, user_id=join_request.user_id, )
            role = Role.objects.filter(team_id=join_request.team_id, role_name='Member').first()
            membership.role_id = role
            membership.save()
        return redirect('team:team_info', pk=join_request.team_id.id)

@login_required(login_url='user:signin')
def decline_invite(request, pk):
    if request.method == 'POST':
        invite = Invite.objects.get(pk=pk)
        if not has_perm('U', 'I', request.user, invite.team_id.id):
            return HttpResponseForbidden()
        invite.status = 'R'
        invite.save()
        return redirect('user:dashboard', u_pk=invite.team_id.id)

@login_required(login_url='user:signin')
def decline_join_request(request, pk):
    if request.method == 'POST':
        join_request = JoinRequest.objects.get(pk=pk)
        if not has_perm('U', 'JR', request.user, join_request.team_id.id):
            return HttpResponseForbidden()
        join_request.status = 'R'
        join_request.save()
        return redirect('user:dashboard', u_pk=join_request.team_id.id)

@login_required(login_url='user:signin')
def leave_team(request, pk):
    membership = Membership.objects.get(user_id=request.user.pk, team_id=pk)
    membership.delete()
    return redirect('user:dashboard', u_pk=request.user.pk)

@login_required(login_url='user:signin')
def permissions(request, pk):
    if not has_perm('R', 'P', request.user, pk):
        return HttpResponseForbidden()
    perms = Permission.objects.filter(team_id=pk).values('user_id__first_name', 'user_id__last_name', 'user_id__pk', 'team_id__name', 'team_id__id', 'permission_name', 'pk')
    return render(request, 'permissions.html', {'perms': perms, 'console': get_console_data(pk, request.user)})

@login_required(login_url='user:signin')
def delete_team(request, pk):
    team = Team.objects.get(id=pk)
    if not has_perm('D', 'T', request.user, pk):
        return HttpResponseForbidden()
    team.delete()
    return redirect('user:dashboard', u_pk=request.user.pk)

@login_required(login_url='user:signin')
def get_todo_list(request, pk):
    #items = Item.objects.using('users').get(team_id=pk)
    items = Item.objects.using('users').filter(team_id=pk)
    return render(request, 'todo_list.html', {'console': get_console_data(pk, request.user), 'items': items})

@login_required(login_url='user:signin')
def create_an_item(request, pk):
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            t=form.save()
            t.team_id=pk
            t.save()
            t.save(using='users')
            return redirect('team:get_todo_list', pk=pk)
    else:
        form = ItemForm()
    return render(request, "item_form.html", {'console': get_console_data(pk, request.user), 'form': form})

@login_required(login_url='user:signin')
def edit_an_item(request, pk, id):
    item = get_object_or_404(Item, pk=id)

    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            t=form.save()
            t.save(using='users')
            return redirect('team:get_todo_list', pk=pk)
    else:
        form = ItemForm(instance=item)
    return render(request, "item_form.html", {'console': get_console_data(pk, request.user), 'form': form})

@login_required(login_url='user:signin')
def toggle_status(request, pk, id):
    item = get_object_or_404(Item, pk=id)
    item.done = not item.done
    item.save(using='users')
    return redirect('team:get_todo_list', pk=pk)

@login_required(login_url='user:signin')
def view_analytics(request, pk):
    if not has_perm('V', 'A', request.user, pk):
        return HttpResponseForbidden()
    allevent = Feedback.objects.filter(teamid=pk).values()
    df = pd.DataFrame(list(allevent))
    desc = df['feedback']
    comment_words = ''
    for val in desc:
        comment_words = comment_words + " " + str(val)
    stopwords = set(STOPWORDS)
 
    wordcloud = WordCloud(width = 800, height = 800,
                    background_color ='white',
                    stopwords = stopwords,
                    min_font_size = 10).generate(comment_words)
    
    # plotting the word cloud image                      

sirius/team/templates/create_sub_team.html
{% extends 'console.html' %}

{% block workspace %}
<div class="form-wrapper flex items-center w-full">
    <div>
        <h2>Sub Team</h2>
        <form method="POST" action="{% url 'team:create_sub_team' pk=console.team.id %}">
            {% csrf_token %}
            {% include 'form.html' with form=form %}
            <input type="submit" value="Create" class="!w-[180px] mx-auto">
        </form>
    </div>
</div>
{% endblock %}

sirius/team/templates/invites.html
{% extends 'console.html' %}

{% block title %}
    {{ team.name }}
{% endblock %}

{% block workspace %}

    <div class="row">
        <div class="col-md-12">
            <h2>Invites</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                    {% for invite in invites %}
                                <a href="{{ url 'team:accept_invite' team_id=team.id invite_id=invite.id }}" class="btn btn-success">Accept</a>
                                <a href="{{ url 'team:decline_invite' team_id=team.id invite_id=invite.id }}" class="btn btn-danger">Decline</a>
                    {% endfor %}
        </div>
    </div>

{% endblock %}

{% endblock %}

sirius/team/templates/item_form.html
{% extends 'console.html' %}
{% block workspace %}
<div class="form-wrapper flex items-center w-full">
    <div>
        <h2>Add/Edit Task</h2>
        <form method="POST" action="">
            {% csrf_token %}
            {% include 'form.html' with form=form %}
            <input type="submit" value="Save" class="!w-[180px] mx-auto !bg-green">
        </form>
    </div>
</div>
{% endblock %}

sirius/team/templates/join_requests.html
{% extends 'console.html' %}

{% load static %}

{% block workspace %}
    <div class="flex w-full justify-center grow">
        <div class="flex w-full flex-col items-center">
            {% for jr in requests %}
                <div class="rounded-lg flex min-w-[500px] w-[64%] flex-row shadow-xl items-center px-[40px] py-[20px]">
                    <div class="w-[100px] h-[100px] rounded-full overflow-clip mr-[18px]">
                        <img src="{% static 'images/avatar.png' %}" />
                    </div>
                    <div class="flex flex-col text-[36px] font-poppins text-grey space-y-[-12px]">
                        <p class="my-auto ">{{ jr.user_id__first_name }}</p>
                        <p class="text-grey/50 text-[18px]">@{{ jr.user_id__username }}</p>
                    </div>
                    {% if "U-JR" in console.perms %}
                    <div class="my-[auto] flex grow justify-end">
                        <form action="{% url 'team:accept_join_request' pk=jr.pk%}" method="POST">
                            {% csrf_token %}
                            <button type="submit"><i class="mr-[50px] fas fa-check-circle text-[50px] text-[#83CE00]"></i></button>
                        </form>
                        <form action="{% url 'team:decline_join_request' pk=jr.pk %}" method="POST">
                            {% csrf_token %}
                            <button type="submit"><i
                                    class="mx-[5px] fa-solid fa-circle-xmark text-[50px] text-[#FF3D00]"></i></button>
                        </form>
                    </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

sirius/team/templates/new_team.html
{% extends 'nav.html' %}

{% load static %}

{% block title %}
    Create a Team
{% endblock %}
    
{% block main %}
<div class="flex flex-row h-[100vh]">
    <div class="form-wrapper grow mt-[10vh]">
        <div>
            <header>
                <h2>Start Your Journey</h2>
            </header>
            <form method="POST" action="{% url 'team:create_team' %}">
                {% csrf_token %}
                {% include 'form.html' with form=form %}
                <input type="submit" value="Create">
            </form>
        </div>
    </div>
    <div class="grow hidden mf:flex mf:w-1/2 justify-center items-start py-[8%]">
        <img src="{% static 'images/woman_working.svg' %}" />
    </div>
</div>
{% endblock %}

sirius/team/templates/permissions.html
{% extends 'console.html' %}

{% block title %}
    {{ team.name }}
{% endblock %}

{% block workspace %}
<div>
<h2> Permissions</h2>
{% for perm in perms %}
    <div class="row">
        <p >
            {{ perm.user_id__firstname }}
        </p>
        <p>
            {{ perm.permission_name }}
        </p>
    </div>
{% endfor %}

<h2>Your Perms</h2>
    {% for perm in perms_list %}
    <p> {{ perm.permission_name }} </p>
    {% endfor %}


</div>
{% endblock %}

sirius/team/templates/team_info.html
{% extends 'console.html' %}

{% load static %}

{% block script %}
    function copyToClipboard()  {
        const copyText = document.getElementById("copy-id");
        const sampleTextarea = document.createElement("textarea");
        document.body.appendChild(sampleTextarea);
        sampleTextarea.value = copyText.getAttribute('title'); //save main text in it
        sampleTextarea.select(); //select textarea contenrs
        document.execCommand("copy");
        document.body.removeChild(sampleTextarea);
    
    }

    document.addEventListener('DOMContentLoaded', function() {
        const copyButton = document.getElementById('copy-button');
        const copyMsg = document.getElementById('copy-msg');
        copyButton.addEventListener("click", (e) => {
            copyMsg.classList.remove("hidden")
            setTimeout(() => {
                copyMsg.classList.add("hidden");
            }, 1500);
        });
    });

{% endblock %}

{% block workspace %}
<div class="flex flex-col justify-start pl-[10%] w-full">
    <div class="w-[200px] h-[200px] rounded-full overflow-clip">
        <img src="https://picsum.photos/300/300" />
    </div>
    <div class="font-poppins font-[300] tracking-[0.06rem] text-grey w-[400px]">
        <p class="text-[18px]">
            {% for parent in console.parents %}
                <a href="{% url 'team:team_info' pk=parent.id %}">
                    <span class="hover:underline">{{parent.name}}</span> / 
                </a>
            {% endfor %}
            <span class="font-[600] text-[40px]">{{console.team.name}}</span>
            <span title="{{ console.team.id }}" class="font-medium cursor-help" id="copy-id">#{{console.team.id|truncatechars:5}}</span>
            <i id="copy-button" class='fa-solid fa-copy cursor-pointer inline-flex w-[40px] h-[40px] rounded-full bg-grey/10 justify-center items-center active:bg-grey/30 hover: ml-[16px]' onclick="copyToClipboard()"></i>
            <span id="copy-msg" class="hidden text-green">Copied!</span>
        </p>
        <p>Since {{ console.team.created_at|date:"d/m/Y" }}</p>
    </div>
    <div class="flex flex-col mf:flex-row gap-x-[128px] gap-y-[32px]">
        <section>
            <h2 class="my-[16px]">Members</h2>
            <ul>
                {% for member in members %}
                    <li class="member-card">
                        <div>
                            <p class="member-name">{{ member.user_id__first_name }} {{ member.user_id__last_name }}</p>
                            <p class="member-username">@{{ member.user_id__username }}</p>
                        </div>
                        <p class="member-role">{{ member.role_id__role_name|upper }}</p>
                    </li>
                {% endfor %}
            </ul>
        </section>
        <section>
            <h2 class="my-[16px]">Teams</h2>
            <ul class="ml-[40px]">
                {% for child in children %}
                    <li class="text-poppins text-[24px] font-[500] my-[16px] hover:scale-[1.02]"><a href="{% url 'team:team_info' pk=child.id %}">{{ child.name }}</a></li>
                {% endfor %}
            </ul>
        </section>
    </div>
</div>
{% endblock %}

sirius/team/templates/todo_list.html
{% extends 'console.html' %}

{% load static %}

{% block workspace %}
    <div class="flex w-full justify-center grow">
        <div class="flex w-full flex-col items-center">
            <div style="height:50px">
                <form method="GET" action="{% url 'team:create_an_item' pk=console.team.id %}" style="height:50px">
                    {% csrf_token %}
                        <button type="submit"><i class="mr-[100px] fas fa-plus-circle text-[50px] text-[#83CE00]"></i>Add new item</button>
                </form>
            </div>
            {% for item in items %}
                <div class="rounded-lg flex min-w-[500px] w-[64%] flex-row shadow-xl items-center px-[40px] py-[20px]">
                    <div class="w-[100px] h-[100px] rounded-full overflow-clip mr-[18px]">
                        <img src="{% static 'images/perms.png' %}" />
                    </div>
                    <div class="flex flex-col text-[36px] font-poppins text-grey space-y-[-12px]">
                        {% if item.done %}
                            <p class="text-grey/50 text-[18px]"><strike>{{ item.name }}</strike></p>
                        {% else %}
                        <p class="text-grey/50 text-[18px]">{{ item.name }}</p>
                        {% endif %}
                    </div>
                    <div class="my-[auto] flex grow justify-end">
                        <form method="GET" action="{% url 'team:edit_an_item' pk=console.team.id id=item.id %}">
                            {% csrf_token %}
                                <button type="submit"><i class="mr-[50px] fas fa-check-circle text-[50px] text-[#83CE00]"></i>Edit</button>
                        </form>
                    </div>
                </div>
                {% empty %}
                <p>You have nothing to do.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}